image:
  file: .devcontainer/Dockerfile
tasks:
  - before: |
      sudo apt update -y
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt install cmake ninja-build git valgrind ccache mold fish python3-setuptools python3-pip cmake-curses-gui nodejs -y
    init: |
      cd ../duckdb
      git pull --tags
      GEN=ninja make debug
    command: |
      ./../duckdb/build/debug/duckdb -c 'pragma version'
workspaceLocation: duckdb_codespace_env/duckdb_codespace_env.code-workspace
additionalRepositories:
  - checkoutLocation: duckdb
    url: https://github.com/Mause/duckdb
  - checkoutLocation: duckdb-web
    url: https://github.com/Mause/duckdb-web
  - checkoutLocation: jdbccts
    url: https://github.com/cwida/jdbccts
gitConfig:
  push.autoSetupRemove: 'true'
  init.defaultBranch: main
  pull.rebase: 'false'
  fetch.prune: 'true'
  fetch.showForcedUpdates: 'true'
vscode:
  extensions:
    - "vscjava.vscode-java-pack"
    # - "ms-vscode.cpptools"
    - "ms-vscode.cmake-tools"
    # - "ms-vscode.cpptools-extension-pack"
