tasks:
  - init: |
      sudo apt update -y
      sudo apt install cmake ninja-build git valgrind -y
      cd duckdb
      GEN=ninja make debug
    command: |
      ./duckdb/build/debug/duckdb -c 'pragma version'
workspaceLocation: duckdb_codespace_env.code-workspace
additionalRepositories:
  - checkoutLocation: /workspace/duckdb_codespace_env/duckdb
    url: https://github.com/Mause/duckdb
  - checkoutLocation: /workspace/duckdb_codespace_env/duckdb-web
    url: https://github.com/Mause/duckdb-web
  - checkoutLocation: /workspace/duckdb_codespace_env/jdbccts
    url: https://github.com/cwida/jdbccts
vscode:
  extensions:
    - "vscjava.vscode-java-pack"
    # - "ms-vscode.cpptools"
    - "ms-vscode.cmake-tools"
    # - "ms-vscode.cpptools-extension-pack"
